# tasks file for redis
---
- name: install | method | check
  fail:
    msg: "Install method {{ redis_install_method }} is not supported"
  when: redis_install_method | string not in redis_install_methods_supported
  tags:
    - configuration
    - redis
    - redis-install-method
    - redis-install-method-check

- include: install-ppa.yml
  when: redis_install_method == 'ppa'
  tags:
    - configuration
    - redis
    - redis-install
    - redis-install-ppa

- include: install-src.yml
  when: redis_install_method != 'ppa'
  tags:
    - configuration
    - redis
    - redis-install
    - redis-install-src

- include: configure.yml
  tags:
    - configuration
    - redis
    - redis-configure

- name: configure | version | get
  command: redis-server --version
  register: redis_binary_version
  changed_when: false
  tags:
    - configuration
    - redis
    - redis-configure
    - redis-configure-version-get

- include: configure-initd.yml
  when: ansible_distribution_version | version_compare('15.04', '<')
  tags:
    - configuration
    - redis
    - redis-configure
    - redis-configure-initd

- include: configure-systemd.yml
  when: ansible_distribution_version | version_compare('15.04', '>=')
  tags:
    - configuration
    - redis
    - redis-configure
    - redis-configure-systemd

- include: kernel.yml
  tags:
    - configuration
    - redis
    - redis-kernel

- name: start and enable service
  service:
    name: "{{ redis_instance_service }}"
    state: started
    enabled: true
  tags:
    - configuration
    - redis
    - redis-start-enable-service
